### ISSUE TITLE
Invalid Request : not accept

### ISSUE THREAD

**Issue by wastu01** [Disane87/threads-api-tester#6]
I am using myself threads account ( public ) 
and double check the  Client ID & Client Secret
but show me that on browser : 
```
{"error_message":"Invalid Request: The  user has not accepted the invite to test the app","error_code":1349245}
```
I check my account is admin

**Comment by wastu01** [comment]
My setting here
<img width="1115" alt="meta threads api Redirect Callback URLs" src="https://github.com/Disane87/threads-api-tester/assets/47618277/ecd57320-43d5-4db0-83bb-92e03d0f1754">

**Comment by Disane87** [comment]
Did you added yourself as tester and accepted this tester request in threads?

**Comment by wastu01** [comment]
> Did you added yourself as tester and accepted this tester request in threads?
@Disane87 I am a admin role

**Comment by Disane87** [comment]
Yes. But only your meta account is admin and your threads account isn't in that account. To do this you need to add it as tester in the thread app on the dev portal and than head over to your threads and accept that invite

**Comment by wastu01** [comment]
hmm I am little bit not understand. have any document or screenshot ?
it show me that  tester is disable 
<img width="1141" alt="image" src="https://github.com/Disane87/threads-api-tester/assets/47618277/f5f64917-2015-4d8a-9e71-ffd3cd7bcad4">


> Yes. But only your meta account is admin and your threads account isn't in that account. To do this you need to add it as tester in the thread app on the dev portal and than head over to your threads and accept that invite

**Comment by wastu01** [comment]
ok, I got it. 
1. application role click add user
2. go to threads app setting accept
<img width="696" alt="Xnip2024-06-26_23-34-13" src="https://github.com/Disane87/threads-api-tester/assets/47618277/545c7779-26e9-4b81-9f74-c63c003940cb">

**Comment by wastu01** [comment]
@Disane87 
it show me 400 error when I get Authorization code.

HTTP request error: 400 Client Error: Bad Request for url: https://graph.threads.net/oauth/access_token
```
{
   "error": {
      "message": "Invalid client_secret: xxxx",
      "type": "OAuthException",
      "code": 101,
      "fbtrace_id": "Aag8zR8jsQe3crhY5jfJYKL"
   }
}
```
I have checked my client secret is correct 
and that error seems output from threads_api.py

**Comment by Disane87** [comment]
Did you used the app client secret or the threads client secret?

**Comment by wastu01** [comment]
> Did you used the app client secret or the threads client secret?

@Disane87  I am using Threads app secret

**Comment by Disane87** [comment]
Could you please post your call here with query params and such? 

This would help me to debug. You can replace your sensitive data with some `<redacted>` markers

**Comment by wastu01** [comment]
@Disane87 OK, here is my callback status
```
(threads-api-tester) ➜  threads-api-tester git:(main) ✗ python ./main.py
Args:  Namespace(client_id=xxxx, client_secret='xxxx')
Client ID: xxxx
Client Secret: xxxx
Redirect URI: https://threads-sample.meta:5000/callback
Opening the authorization URL in your browser: https://threads.net/oauth/authorize?client_id=xxxx&redirect_uri=https://threads-sample.meta:5000/callback&scope=threads_basic,threads_content_publish&response_type=code
 * Serving Flask app 'src.main'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on https://127.0.0.1:5000
Press CTRL+C to quit
Waiting for the authorization code...
Received auth code: xxxx
127.0.0.1 - - [27/Jun/2024 20:04:01] "GET /callback?code=xxxx
HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 20:04:01] "GET /favicon.ico HTTP/1.1" 404 -
HTTP request error: 400 Client Error: Bad Request for url: https://graph.threads.net/oauth/access_token
127.0.0.1 - - [27/Jun/2024 20:04:07] "GET /tokens HTTP/1.1" 200 -

```
<img width="544" alt="Xnip2024-06-27_20-04-11" src="https://github.com/Disane87/threads-api-tester/assets/47618277/49bf1f86-d936-42d4-b21b-584d35fd8012">

**Comment by Disane87** [comment]
Are there any logs after that?

**Comment by wastu01** [comment]
@Disane87  only brower show me this info, and terminal not show anything output

```
HTTP request error: 400 Client Error: Bad Request for url: https://graph.threads.net/oauth/access_token

{
   "error": {
      "message": "Invalid client_secret: xxxx",
      "type": "OAuthException",
      "code": 101,
      "fbtrace_id": "AxEsng5WNub-pvxc62rX9ax"
   }
}
```

**Comment by Disane87** [comment]
That must be an issue with your secrets. The tester works pretty flawlessly so I assume there is something wrong In your environment. 

Could you please double check that? I know it’s a bit odd but it seems to me there is something wrong with your threads app.

**Comment by wastu01** [comment]
I reset threads sercet to try again and it works ! thanks !

**Comment by wastu01** [comment]
@Disane87 
i find the last 6 post is combine post and repost, and the image can not render, is that right ?

**Comment by Disane87** [comment]
Glad it worked out for you! Have fun with it

**Comment by Disane87** [comment]
> @Disane87 
> 
> i find the last 6 post is combine post and repost, and the image can not render, is that right ?

Thats right, I only implemented text for testing purposes. 

All posts are returned by the API, they are only differentiated by the type 

Glad it's working now :)

**Comment by wastu01** [comment]
Got it ! as I am newbie to learn api, next I will research your code and meta docuement to learn more. tks for sharing this demo. it helps me a lot.
https://developers.facebook.com/docs/threads/posts

**Comment by wastu01** [comment]
I find Short-lived token and Long-lived token is same.
