### ISSUE TITLE
Displaying Images for Carousel Posts in Threads API

### ISSUE THREAD

**Issue by wastu01** [Disane87/threads-api-tester#7]
For single image posts, I use the following code snippet to display the image:
`<img src="{{ media['media_url'] }}" alt="Post Image">`
<img width="365" alt="Xnip2024-06-28_22-58-25" src="https://github.com/Disane87/threads-api-tester/assets/47618277/4ee572a7-5581-4e10-b91f-92655553338a">
This works fine for single images, but I am unsure how to access and display the media_url for each image in a carousel post. The carousel posts have multiple child images, and I'm not clear on how to iterate over these children to display all associated images.

**Comment by Disane87** [comment]
I never worked with carousel. Sorry! You have to consult the docs for this.
